// Auto-generated from "Epl Start list June 2026.xlsx" — sheet "60-70 cm" (EPL 2026, Class SJ1).
// 67 riders. Used to populate the rider-picker dropdown in the show jumping scoring sheet.
export type StartListRider = {
  sl: number;
  name: string;
  horse: string;
  category: string;
  club: string;
};

export const SJ1_60_70_RIDERS: StartListRider[] = [
  { sl: 1, name: "Advika B", horse: "Austin", category: "SUB-JUNIOR (Age 14 and Below)", club: "Goodwill" },
  { sl: 2, name: "ADVIK B", horse: "Klaver", category: "SUB-JUNIOR (Age 14 and Below)", club: "Covai Stables" },
  { sl: 3, name: "Nihaan G", horse: "Tara", category: "SUB-JUNIOR (Age 14 and Below)", club: "Covai Stables" },
  { sl: 4, name: "Akshara", horse: "Startina", category: "SUB-JUNIOR (Age 14 and Below)", club: "EIRS" },
  { sl: 5, name: "Khyathi R", horse: "ZARA", category: "JUNIOR (Age 15 to 18)", club: "Covai Stables" },
  { sl: 6, name: "DHRUV PRATAP  SINGH", horse: "DASHING GREY", category: "SUB-JUNIOR (Age 14 and Below)", club: "FSS" },
  { sl: 7, name: "KESAR BAFNA", horse: "RING TONE", category: "SUB-JUNIOR (Age 14 and Below)", club: "FSS" },
  { sl: 8, name: "DHANVI CHERUVU", horse: "CHIEF OF COMMAND", category: "SUB-JUNIOR (Age 14 and Below)", club: "FSS" },
  { sl: 9, name: "Yuvaan Sarang", horse: "Bazel", category: "SUB-JUNIOR (Age 14 and Below)", club: "Goodwill" },
  { sl: 10, name: "Srujana Gore", horse: "Pharoah", category: "SUB-JUNIOR (Age 14 and Below)", club: "Goodwill" },
  { sl: 11, name: "Shriya Rao", horse: "Austin", category: "SUB-JUNIOR (Age 14 and Below)", club: "Goodwill" },
  { sl: 12, name: "Abdul Rahman Shariff", horse: "Jai Vikram", category: "OPEN (Age 19 and Above)", club: "DHRA" },
  { sl: 13, name: "Venugopal", horse: "Pirate", category: "OPEN (Age 19 and Above)", club: "DHRA" },
  { sl: 14, name: "Anshika Karale", horse: "Phoenix", category: "SUB-JUNIOR (Age 14 and Below)", club: "Goodwill" },
  { sl: 15, name: "DHRUV PRATAP  SINGH", horse: "RING TONE", category: "SUB-JUNIOR (Age 14 and Below)", club: "FSS" },
  { sl: 16, name: "KESAR BAFNA", horse: "CLOUD 9", category: "SUB-JUNIOR (Age 14 and Below)", club: "FSS" },
  { sl: 17, name: "SENTHILNATHAN KUMARAVEL", horse: "meera", category: "OPEN (Age 19 and Above)", club: "Covai Stables" },
  { sl: 18, name: "Ishanvi Pranav Bathija", horse: "ZARA", category: "JUNIOR (Age 15 to 18)", club: "Covai Stables" },
  { sl: 19, name: "pranjal  raturi", horse: "mirudhan", category: "OPEN (Age 19 and Above)", club: "Covai Stables" },
  { sl: 20, name: "Khyathi R", horse: "klaver", category: "JUNIOR (Age 15 to 18)", club: "Covai Stables" },
  { sl: 21, name: "Mohammad Umar", horse: "War Soldier", category: "SUB-JUNIOR (Age 14 and Below)", club: "REA" },
  { sl: 22, name: "Harshvardhan Apte", horse: "William Wallace", category: "SUB-JUNIOR (Age 14 and Below)", club: "Goodwill" },
  { sl: 23, name: "Shriya Rao", horse: "Pharoah", category: "SUB-JUNIOR (Age 14 and Below)", club: "Goodwill" },
  { sl: 24, name: "Khyati Vatsya", horse: "Austin", category: "SUB-JUNIOR (Age 14 and Below)", club: "Goodwill" },
  { sl: 25, name: "Ananya", horse: "Long Range", category: "SUB-JUNIOR (Age 14 and Below)", club: "Zippy" },
  { sl: 26, name: "Amina Lakdawala", horse: "Velocity", category: "OPEN (Age 19 and Above)", club: "RTLA" },
  { sl: 27, name: "Vishwa", horse: "Hercules", category: "OPEN (Age 19 and Above)", club: "Zippy" },
  { sl: 28, name: "Nitya Singhal", horse: "Acaster", category: "JUNIOR (Age 15 to 18)", club: "REA" },
  { sl: 29, name: "Avni Mali", horse: "Delta", category: "JUNIOR (Age 15 to 18)", club: "Kings Farm" },
  { sl: 30, name: "Omkar Akhade", horse: "Pissarro", category: "OPEN (Age 19 and Above)", club: "Goodwill" },
  { sl: 31, name: "Vishwa", horse: "Rusty", category: "OPEN (Age 19 and Above)", club: "Zippy" },
  { sl: 32, name: "Swapnil Sane", horse: "Valli", category: "OPEN (Age 19 and Above)", club: "EIRS" },
  { sl: 33, name: "Barath Manoharan", horse: "Qina", category: "OPEN (Age 19 and Above)", club: "ECE" },
  { sl: 34, name: "Sai", horse: "Santiago", category: "OPEN (Age 19 and Above)", club: "Zippy" },
  { sl: 35, name: "Yuvan Tummala", horse: "Coco", category: "SUB-JUNIOR (Age 14 and Below)", club: "Kings Farm" },
  { sl: 36, name: "Gautam Amit Ahirrao", horse: "Silver", category: "JUNIOR (Age 15 to 18)", club: "Kings Farm" },
  { sl: 37, name: "Naisha Vithun", horse: "Explosion", category: "SUB-JUNIOR (Age 14 and Below)", club: "ASC Centre North" },
  { sl: 38, name: "Yuvan", horse: "Helico", category: "SUB-JUNIOR (Age 14 and Below)", club: "ECE" },
  { sl: 39, name: "Sai", horse: "Knights", category: "OPEN (Age 19 and Above)", club: "Zippy" },
  { sl: 40, name: "saurya", horse: "big dream", category: "SUB-JUNIOR (Age 14 and Below)", club: "Covai Stables" },
  { sl: 41, name: "Arnitha", horse: "Rusty", category: "SUB-JUNIOR (Age 14 and Below)", club: "Zippy" },
  { sl: 42, name: "Barath Manoharan", horse: "Lotus", category: "OPEN (Age 19 and Above)", club: "ECE" },
  { sl: 43, name: "Avni Mali", horse: "Delta", category: "JUNIOR (Age 15 to 18)", club: "Kings Farm" },
  { sl: 44, name: "Swapnil Sane", horse: "Mathaiyus", category: "OPEN (Age 19 and Above)", club: "EIRS" },
  { sl: 45, name: "Vinay", horse: "Zafira", category: "OPEN (Age 19 and Above)", club: "EIRS" },
  { sl: 46, name: "Yuvan Tummala", horse: "Silver", category: "SUB-JUNIOR (Age 14 and Below)", club: "Kings Farm" },
  { sl: 47, name: "Gautam Amit Ahirrao", horse: "Red Rum", category: "JUNIOR (Age 15 to 18)", club: "Kings Farm" },
  { sl: 48, name: "pranjal  raturi", horse: "meera", category: "OPEN (Age 19 and Above)", club: "Covai Stables" },
  { sl: 49, name: "Md Awes Karni", horse: "Coco", category: "OPEN (Age 19 and Above)", club: "Kings Farm" },
  { sl: 50, name: "ADVIK B", horse: "mirudhan", category: "SUB-JUNIOR (Age 14 and Below)", club: "Covai Stables" },
  { sl: 51, name: "Nihaan G", horse: "klaver", category: "SUB-JUNIOR (Age 14 and Below)", club: "Covai Stables" },
  { sl: 52, name: "kavin m", horse: "Tara", category: "SUB-JUNIOR (Age 14 and Below)", club: "Covai Stables" },
  { sl: 53, name: "DHANVI CHERUVU", horse: "DASHING GREY", category: "SUB-JUNIOR (Age 14 and Below)", club: "FSS" },
  { sl: 54, name: "Mohammad Umar", horse: "Ultimate Warrior", category: "SUB-JUNIOR (Age 14 and Below)", club: "REA" },
  { sl: 55, name: "Rishaan Suvarna", horse: "War Soldier", category: "SUB-JUNIOR (Age 14 and Below)", club: "REA" },
  { sl: 56, name: "Shiven Ghosh", horse: "Acaster", category: "SUB-JUNIOR (Age 14 and Below)", club: "REA" },
  { sl: 57, name: "Manil Rao", horse: "Rajkumar", category: "JUNIOR (Age 15 to 18)", club: "ARPA" },
  { sl: 58, name: "Alwin Lara", horse: "Kalpana", category: "OPEN (Age 19 and Above)", club: "ARPA" },
  { sl: 59, name: "DHRUV PRATAP  SINGH", horse: "CHIEF OF COMMAND", category: "SUB-JUNIOR (Age 14 and Below)", club: "FSS" },
  { sl: 60, name: "KESAR BAFNA", horse: "DASHING GREY", category: "SUB-JUNIOR (Age 14 and Below)", club: "FSS" },
  { sl: 61, name: "Omkar Akhade", horse: "Vortex Wind", category: "OPEN (Age 19 and Above)", club: "Goodwill" },
  { sl: 62, name: "Venugopal", horse: "Pirate", category: "OPEN (Age 19 and Above)", club: "DHRA" },
  { sl: 63, name: "Rahul Mohanty", horse: "War Soldier", category: "OPEN (Age 19 and Above)", club: "REA" },
  { sl: 64, name: "Gautam Amit Ahirrao", horse: "Coco", category: "JUNIOR (Age 15 to 18)", club: "Kings Farm" },
  { sl: 65, name: "Muhammad Raheesh", horse: "Kalpana", category: "SUB-JUNIOR (Age 14 and Below)", club: "ARPA" },
  { sl: 66, name: "Rishaan Suvarna", horse: "Ultimate Warrior", category: "SUB-JUNIOR (Age 14 and Below)", club: "REA" },
  { sl: 67, name: "Md Awes Karni", horse: "Delta", category: "OPEN (Age 19 and Above)", club: "Kings Farm" },
];
