import { type Movement, type TestConfig } from "./types";

export const movements: Movement[] = [
  { no: "1",  letters: "A\nX\n\nXC",           test: "Enter in collected canter\nHalt - immobility - salute\nProceed in collected trot\nCollected trot",                                                                                                                                    coefficient: 1, directive: "Quality of paces, halt, and transitions. Straightness. Contact and poll." },
  { no: "2",  letters: "C\nHXF\nF\nFA",         test: "Track to the left\nExtended trot\nCollected trot\nCollected trot",                                                                                                                                                                   coefficient: 1, directive: "Regularity, elasticity, balance, energy of hindquarters, overtrack. Lengthening of frame. Both transitions. Collection." },
  { no: "3",  letters: "A\nDX",                  test: "Down the centre line\nShoulder-in right",                                                                                                                                                                                           coefficient: 1, directive: "Regularity and quality of trot; bend and constant angle. Collection, balance, and fluency." },
  { no: "4",  letters: "X",                      test: "Volte right (8 m Ø)",                                                                                                                                                                                                              coefficient: 1, directive: "Regularity and quality of trot, collection, and balance. Bend; size and shape of volte." },
  { no: "5",  letters: "XM\nMC",                 test: "Half-pass to the right\nCollected trot",                                                                                                                                                                                           coefficient: 2, directive: "Regularity and quality of trot, uniform bend, collection, balance, fluency, crossing of legs." },
  { no: "6",  letters: "C",                      test: "Halt - immobility\nRein back 5 steps and immediately proceed in collected trot",                                                                                                                                                    coefficient: 1, directive: "Quality of halt and transitions. Throughness, fluency, straightness. Accuracy in number of diagonal steps." },
  { no: "7",  letters: "HX",                     test: "Half-pass to the left",                                                                                                                                                                                                            coefficient: 2, directive: "Regularity and quality of trot, uniform bend, collection, balance, fluency, crossing of legs." },
  { no: "8",  letters: "X",                      test: "Volte left (8 m Ø)",                                                                                                                                                                                                               coefficient: 1, directive: "Regularity and quality of trot, collection, and balance. Bend; size and shape of volte." },
  { no: "9",  letters: "XD\nD\nA",               test: "Shoulder-in left\nOn centre line\nTrack to the right",                                                                                                                                                                             coefficient: 1, directive: "Regularity and quality of trot; bend and constant angle. Collection, balance, and fluency." },
  { no: "10", letters: "KR",                     test: "Medium trot",                                                                                                                                                                                                                      coefficient: 1, directive: "Regularity, elasticity, balance, engagement of hindquarters, lengthening of steps and frame. Both transitions. Differentiation from extended trot." },
  { no: "11", letters: "R\nRMGH",                test: "Collected walk\nCollected walk",                                                                                                                                                                                                   coefficient: 2, directive: "Regularity, suppleness of back, activity, shortening and heightening of steps, self-carriage. Transition into walk." },
  { no: "12", letters: "HB(P)",                  test: "Extended walk",                                                                                                                                                                                                                    coefficient: 2, directive: "Regularity, suppleness of back, activity, overtrack, freedom of shoulder, stretching to the bit." },
  { no: "13", letters: "Before P\nP\nPFA",        test: "Collected walk\nProceed in collected canter right\nCollected canter",                                                                                                                                                              coefficient: 1, directive: "Precise execution and fluency of transitions. Quality of canter." },
  { no: "14", letters: "A\nBetween D&G\n\n\n\nG\nC", test: "Down the centre line\n3 half-passes 5 m to either side of the centre line with flying change of leg at each change of direction starting and ending to the right\nFlying change of leg\nTrack to the left",                   coefficient: 2, directive: "Quality of canter. Uniform bend, collection, balance, fluency from side to side. Symmetrical execution. Quality of flying changes." },
  { no: "15", letters: "HXF",                    test: "Extended canter",                                                                                                                                                                                                                  coefficient: 1, directive: "Quality of canter, impulsion, lengthening of strides and frame. Balance, uphill tendency, straightness." },
  { no: "16", letters: "F\nFAK",                 test: "Collected canter and flying change of leg\nCollected canter",                                                                                                                                                                       coefficient: 1, directive: "Quality of flying change on diagonal. Precise, smooth execution of transition. Collection." },
  { no: "17", letters: "KXM\nMCH",               test: "On the diagonal 5 flying changes of leg every 3rd stride\nCollected canter",                                                                                                                                                       coefficient: 1, directive: "Correctness, balance, fluency, uphill tendency, straightness. Quality of canter before and after." },
  { no: "18", letters: "H(B)\nI",                test: "On the diagonal\nPirouette to the left",                                                                                                                                                                                           coefficient: 2, directive: "Collection, self-carriage, balance, size, flexion, and bend. Correct number of strides (6–8). Quality of canter before and after." },
  { no: "19", letters: "B\nBefore & after B",    test: "Flying change of leg\nCollected canter",                                                                                                                                                                                           coefficient: 1, directive: "Correctness, balance, fluency, uphill tendency, straightness of flying change." },
  { no: "20", letters: "B(K)\nL",                test: "On the diagonal\nPirouette to the right",                                                                                                                                                                                          coefficient: 2, directive: "Collection, self-carriage, balance, size, flexion, and bend. Correct number of strides (6–8). Quality of canter before and after." },
  { no: "21", letters: "K\nKAF",                 test: "Flying change of leg\nCollected canter",                                                                                                                                                                                           coefficient: 1, directive: "Correctness, balance, fluency, uphill tendency, straightness of flying change. Quality of canter." },
  { no: "22", letters: "FXH\nHC",                test: "On the diagonal 7 flying changes of leg every 2nd stride\nCollected canter",                                                                                                                                                       coefficient: 1, directive: "Correctness, balance, fluency, uphill tendency, straightness. Quality of canter before and after." },
  { no: "23", letters: "C\nCM",                  test: "Collected trot\nCollected trot",                                                                                                                                                                                                   coefficient: 1, directive: "Fluency; precise, smooth execution of transition. Collection." },
  { no: "24", letters: "MXK\nK\nKA",             test: "Extended trot\nCollected trot\nThe collected trot",                                                                                                                                                                                coefficient: 1, directive: "Regularity, elasticity, balance, energy of hindquarters, overtrack. Lengthening of frame. Both transitions. Collection." },
  { no: "25", letters: "A\nX",                   test: "Down the centre line\nHalt - immobility - salute",                                                                                                                                                                                 coefficient: 1, directive: "Quality of pace, halt, and transition. Straightness. Contact and poll." },
];

export const config: TestConfig = {
  label: "Intermediate I",
  appendix: "Appendix 'A'",
  abbr: "Int I",
  subtitle: "Time 5′30″ · Minimum age of horse: 7 years",
  movements,
  otherErrorPenalty: 0.5,
  courseErrors: [
    { label: "No error",          value: 0 },
    { label: "1st error · −2%",   value: 2 },
    { label: "2nd error · Elim.", value: -1 },
  ],
};
