import { type Movement, type TestConfig } from "./types";

export const movements: Movement[] = [
  { no: "1",  letters: "A\nX",              test: "Enter in collected trot\nHalt - immobility - salute",                                                                                                                     coefficient: 1, directive: "Correctness of trot and transition. Precision of centre line and halt. Preparation of halt. Immobility, straightness. Contact and poll." },
  { no: "2",  letters: "X\nXC",             test: "Proceed in collected trot\nCollected trot",                                                                                                                               coefficient: 1, directive: "Promptness of depart, quality of trot. Straightness. Contact and poll." },
  { no: "3",  letters: "C\nHSE",            test: "Track to the left\nShoulder-in left",                                                                                                                                    coefficient: 2, directive: "Regularity and quality of trot; uniformed bend and constant angle. Collection, balance, and fluency." },
  { no: "4",  letters: "EX\nXB",            test: "Half volte left (10m Ø)\nHalf volte right (10m Ø)",                                                                                                                      coefficient: 1, directive: "Regularity, balance, energy, bend. Fluency of the change of bend and direction. Symmetrical design of ½ voltes." },
  { no: "5",  letters: "BPF\nFAK",          test: "Shoulder-in right\nCollected trot",                                                                                                                                      coefficient: 2, directive: "Regularity and quality of trot; uniformed bend and constant angle. Collection, balance, and fluency." },
  { no: "6",  letters: "KXM\nM",            test: "Medium trot\nCollected trot",                                                                                                                                            coefficient: 1, directive: "Regularity, balance, engagement, groundcover. Lengthening of frame. Straightness." },
  { no: "7",  letters: "\nMC",              test: "Transitions at K and M\nCollected trot",                                                                                                                                 coefficient: 1, directive: "Fluency and balance of both transitions. Regularity of trot." },
  { no: "8",  letters: "CHG",               test: "Medium walk",                                                                                                                                                            coefficient: 1, directive: "Regularity, suppleness of back, activity, groundcover, freedom in shoulders. Straightness." },
  { no: "9",  letters: "Between G&M",       test: "Turn on the haunches to the left, proceed in medium walk",                                                                                                               coefficient: 2, directive: "Regularity, activity, fluency, size, flexion, and bend. Forward tendency, maintenance of fourbeat." },
  { no: "10", letters: "Between G&H",       test: "Turn on the haunches to the right, proceed in medium walk",                                                                                                              coefficient: 2, directive: "Regularity, activity, fluency, size, flexion, and bend. Forward tendency, maintenance of fourbeat." },
  { no: "11", letters: "GMC",               test: "Medium walk",                                                                                                                                                            coefficient: 1, directive: "Regularity, suppleness of back, activity, groundcover, freedom in shoulders. Straightness." },
  { no: "12", letters: "C\nCH",             test: "Proceed in collected canter\nCollected canter",                                                                                                                          coefficient: 1, directive: "Fluency and balance of transition. Quality of canter." },
  { no: "13", letters: "HEK\nK",            test: "Medium canter\nCollected canter",                                                                                                                                        coefficient: 1, directive: "Lengthening of strides and frame. Balance, uphill tendency, straightness." },
  { no: "14", letters: "KA",                test: "Transitions at H & K\nCollected canter",                                                                                                                                 coefficient: 1, directive: "Fluency and balance of both transitions. Quality of canter." },
  { no: "15", letters: "AX",                test: "Serpentine with two loops, the 1st loop in true canter, the 2nd loop in counter canter",                                                                                 coefficient: 1, directive: "Quality and collection of (counter)canter. Balance, self-carriage. Correct flexion and bend. Fluency of the change of direction. Symmetrical design." },
  { no: "16", letters: "X",                 test: "Simple change of leg from counter canter to counter canter",                                                                                                             coefficient: 2, directive: "Promptness, fluency and balance of transitions. 3–5 clear walk steps. Straightness." },
  { no: "17", letters: "XC\nCMR",          test: "Serpentine with two loops, the 1st loop in counter canter, the 2nd loop in true canter\nCollected canter",                                                              coefficient: 1, directive: "Quality and collection of (counter)canter. Balance, self-carriage. Correct flexion and bend. Fluency of the change of direction. Symmetrical design." },
  { no: "18", letters: "RI\nI\nIS\nS\nE",  test: "Half volte right (10 m Ø)\nSimple change of leg\nHalf volte left (10 m Ø)\nCollected canter",                                                                           coefficient: 2, directive: "Promptness, fluency, balance of transitions. 3–5 clear walk steps. Straightness. Quality of canter and bend in the ½ voltes. Symmetrical design." },
  { no: "19", letters: "E\nVPV\nVP\nPV\nVKA", test: "Working trot\nCircle (20 m Ø)\nLet the horse stretch on a long rein\nRetake the reins\nWorking trot",                                                                coefficient: 2, directive: "Maintenance of rhythm and balance. Gradually stretching forward downward of neck. Retaking the reins without resistance. Size and shape of circle." },
  { no: "20", letters: "A\nX",              test: "Down the centre line\nHalt – immobility – salute",                                                                                                                       coefficient: 1, directive: "Quality of trot, straightness and balance into the halt. Contact and poll." },
];

export const config: TestConfig = {
  label: "Medium / Senior I",
  appendix: "Appendix 'E'",
  abbr: "MS1",
  subtitle: "Time 6.30 min · Minimum age of horse: 6 years",
  movements,
  otherErrorPenalty: 0.5,
};
