import { type Movement, type TestConfig } from "./types";

export const movements: Movement[] = [
  { no: "1",  letters: "A\nX",          test: "Enter in collected canter\nHalf-immobility – salute\nProceed in collected trot",                                                                                     coefficient: 1, directive: "The entry. The halt and the transitions from the canter to the halt and from the halt to the trot." },
  { no: "2",  letters: "C\nR",          test: "Track right\nVolte right 8 m",                                                                                                                                        coefficient: 1, directive: "The collection. The bend. The regularity and the balance." },
  { no: "3",  letters: "R P",           test: "Shoulder-in right",                                                                                                                                                   coefficient: 1, directive: "The angle and bend of the horse. The collection. The regularity." },
  { no: "4",  letters: "P L\nL R",      test: "Half-volte right 10 m\nHalf-pass right",                                                                                                                              coefficient: 1, directive: "The correctness and regularity. The carriage and bend. The balance. The collection." },
  { no: "5",  letters: "M\nG\nH",       test: "Turn left\nHalf-immobility 5 seconds\nProceed in collected trot\nTurn left",                                                                                          coefficient: 1, directive: "The halt, the immobility and transitions." },
  { no: "6",  letters: "S",             test: "Volte left 8 m",                                                                                                                                                      coefficient: 1, directive: "The collection. The bend. The regularity and the balance." },
  { no: "7",  letters: "S V",           test: "Shoulder-in left",                                                                                                                                                    coefficient: 1, directive: "The angle and bend of the horse. The collection. The regularity." },
  { no: "8",  letters: "V L\nL S\nS H C M", test: "Half-volte left 10 m\nHalf-pass left\nCollected trot",                                                                                                           coefficient: 1, directive: "The correctness and regularity. The carriage and bend. The balance. The collection." },
  { no: "9",  letters: "M X K\nK",      test: "Medium trot\nCollected trot",                                                                                                                                         coefficient: 1, directive: "The lengthening and regularity of the steps. The balance. The transitions." },
  { no: "10", letters: "A",             test: "Halt – rein back 5 steps\nImmediately proceed in collected trot",                                                                                                     coefficient: 1, directive: "The halt. The rein back. The transitions." },
  { no: "11", letters: "F X H\nH",      test: "Extended trot\nCollected trot",                                                                                                                                       coefficient: 1, directive: "The lengthening of the frame. The extension and regularity of the steps. The transitions." },
  { no: "12", letters: "C\nBefore M\nM\nM C H", test: "Medium walk\nShorten the steps\nHalf pirouette right\nMedium walk",                                                                                          coefficient: 1, directive: "The shortening of the steps. The regularity of the half pirouette." },
  { no: "13", letters: "Before H\nH",   test: "Shorten the steps\nHalf pirouette left",                                                                                                                             coefficient: 1, directive: "The regularity of the half pirouette." },
  { no: "14", letters: "",              test: "Medium walk (C M C H)",                                                                                                                                               coefficient: 1, directive: "The lengthening and regularity of the steps." },
  { no: "15", letters: "H C M\nM V",    test: "Change rein in extended walk",                                                                                                                                        coefficient: 1, directive: "The lengthening of the frame and of the step. The regularity." },
  { no: "16", letters: "V\nK\nK A F",   test: "Medium walk\nProceed in collected canter left\nCollected canter",                                                                                                     coefficient: 1, directive: "The transition. The collection. The balance." },
  { no: "17", letters: "F M\nM",        test: "Medium canter\nCollected canter",                                                                                                                                     coefficient: 1, directive: "The lengthening. The transitions." },
  { no: "18", letters: "S I\nI\nI R",   test: "Half-volte left 10 m\nSimple change of leg\nHalf-volte right 10 m",                                                                                                  coefficient: 1, directive: "The transitions from canter to walk and from walk to canter." },
  { no: "19", letters: "R X V\nV A",    test: "Change rein in collected canter\nCounter canter",                                                                                                                     coefficient: 1, directive: "The balance. The counter canter." },
  { no: "20", letters: "A",             test: "Flying change of leg",                                                                                                                                                coefficient: 1, directive: "The flying change of leg." },
  { no: "21", letters: "P X S\nS C",    test: "Change rein in collected trot\nCounter canter",                                                                                                                       coefficient: 1, directive: "The balance. The counter canter." },
  { no: "22", letters: "C",             test: "Flying change of leg",                                                                                                                                                coefficient: 1, directive: "The flying change of leg." },
  { no: "23", letters: "M F\nF A K V",  test: "Medium canter\nCollected canter",                                                                                                                                     coefficient: 1, directive: "The lengthening. The transition." },
  { no: "24", letters: "V L\nL\nL P",   test: "Half-volte right 10 m\nSimple change of leg\nHalf-volte left 10 m",                                                                                                  coefficient: 1, directive: "The transition from canter to walk and from walk to canter." },
  { no: "25", letters: "P M C",         test: "Collected canter",                                                                                                                                                    coefficient: 1, directive: "The collection. The straightness." },
  { no: "26", letters: "C\nH X F\nF",   test: "Collected trot\nExtended trot\nCollected trot",                                                                                                                       coefficient: 1, directive: "The lengthening of the frame and regularity of the steps. The balance. The transitions." },
  { no: "27", letters: "A\nX",          test: "Down the centre line\nHalt – immobility – salute",                                                                                                                    coefficient: 1, directive: "The straightness, the transitions and the halt." },
];

export const config: TestConfig = {
  label: "Young Rider",
  appendix: "Appendix A",
  abbr: "YR",
  subtitle: "Time 6′30″ · Minimum age of horse: 6 years",
  movements,
};
